# Generated by Django 5.0.6 on 2026-06-22 08:09

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0002_alter_propertyimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
