# Generated by Django 5.0.6 on 2026-06-22 10:53

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0003_change_location_embedding_to_384_dimensions'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='location',
            index=pgvector.django.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='location_embedding_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
