# Generated by Django 5.0.6 on 2026-06-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0004_add_hnsw_index_to_location_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
